version: "3.7"

services:
  nodejs:
    build:
      context: .
      target: build 
    image: sanctuary-api-dev 
    container_name: sanctuary-api-dev
    restart: unless-stopped
    env_file: .env 
    environment:
      - MYSQL_HOSTNAME=db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - .:/app 
    networks:
      - app-network
    depends_on:
      - db
    command: sh -c "npm run migrate && npm run seed && npm run dev" 

  db:
    platform: linux/amd64
    image: mysql:5.6.44
    container_name: db
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: